Custom binary sensor
omerfaruk-aran/esphome_samsung_hvac_bus pull request #162
Opened 2024-08-18 17:37 UTC by north3221

I've created this to compliment the custom sensors, so we can have binary sensors for some of the heat pump variables.

Needs a bit of a review, its generally fine I think apart from how I am handling the call to process the message, currently with an type (int) variable. If we think that's a good way of doing it, could firm that up with an enum, but interested on if there is a view of a better way?

2024-08-18 17:41 UTC, north3221 commented on components/samsung_ac/protocol_nasa.cpp
@atanasenko @lanwin interested on what you think the best way to handle the different custom sensor types is? If you think this way is ok I could create as enum, but any better ideas?

2024-10-09 16:15 UTC, lanwin requested changes
Can you please also add an example to the example.yaml

2024-10-09 16:15 UTC, lanwin commented on components/samsung_ac/samsung_ac.h
> +	  void /*MessageTarget::*/ set_custom_binary_sensor(const std::string address, uint16_t message_number, bool value) override
Can you please check the indentation here.

2024-10-09 16:15 UTC, lanwin commented on components/samsung_ac/protocol_nasa.cpp
Yes. In main I removed the custom parameter compleatly and just call set_custom_sensor every time. If there is no custom sensor, this does nothing. 

So the best would be if you do the same.

2024-12-10 19:18 UTC, kristo2301 commented
Hello, could you please put example how to use custom binary sensor in *.yaml?
i would like to play with heat pump to grab more parameters

2026-05-29 11:25 UTC, north3221 commented
I’ve come back to this and reworked it based on the earlier feedback.

Instead of adding a separate custom_binary_sensor block, this now extends the existing custom_sensor mechanism with type: binary.

It is rebased on current main and keeps the existing protocol behaviour where decoded messages call set_custom_sensor, with the device layer updating the matching configured entity if present.

Binary custom sensors publish false when the decoded value is 0 and true for any non-zero value, matching the behaviour from my original local implementation.

I’ve also updated example.yaml to show type: binary usage and moved the NASA heat pump water examples under the indoor device section.

2026-05-29 11:45 UTC, north3221 commented
> Hello, could you please put example how to use custom binary sensor in *.yaml? i would like to play with heat pump to grab more parameters

Now that I have addressed the comments and updated this, I've added examples to the examples.yaml

Better late than never :-)

2026-05-29 11:54 UTC, omerfaruk-aran commented
Thanks for coming back to this and reworking it.

The current direction looks good to me: extending the existing `custom_sensor` block with `type: binary` is cleaner than introducing a separate `custom_binary_sensor` block, and it keeps the protocol layer behavior unchanged.

A couple of points before merge:

1. Please make the example comment slightly clearer that `message: 0x4087` is only an example/discovered bus message and must be replaced by the user’s own message number.
2. Please keep the documented binary behavior explicit: decoded value `0` publishes `false`, any non-zero value publishes `true`.
3. Since there is still an old `CHANGES_REQUESTED` review on the PR, I’d prefer to wait for a fresh approval from @lanwin or explicitly confirm that the previous review comments are now addressed.

Technically this looks low-risk and backward-compatible for existing numeric `custom_sensor` users.

2026-05-29 12:17 UTC, north3221 commented
Thanks, I’ve updated the example comments to make it clearer that the message IDs are examples/discovered bus messages and should be replaced with values from the user’s own device.

I’ve also kept the binary behaviour explicit in the example: decoded value `0` publishes `false`, and any non-zero decoded value publishes `true`.

I’m also using the existing numeric `custom_sensor` behaviour in my own config and can confirm this change is backward-compatible there: entries without `type: binary` continue to be created as normal numeric sensors.

Agreed on waiting for a fresh approval / confirmation from @lanwin that the earlier review comments are now addressed.

2026-05-29 12:22 UTC, omerfaruk-aran commented
Thanks for the update. This addresses my concerns.

Since the PR is still blocked by the previous `CHANGES_REQUESTED` review, let's wait for @lanwin to re-review or confirm that the earlier comments are now addressed.

I will not bypass the required review unless there is a clear maintainer decision to do so.

2026-06-19 13:49 UTC, north3221 commented
@lanwin are you able to take a look to confirm this one is ok to merge please?

2026-07-04 19:41 UTC, lanwin approved these changes
From my point of view it looks good. But @omerfaruk-aran should decide if he wants to support it.

2026-07-06 23:17 UTC, merged

2026-07-06 23:18 UTC, omerfaruk-aran commented
Thanks for the update and thanks @lanwin for the review.

Merged. This adds useful binary support while keeping the existing custom_sensor behavior backward-compatible.